seed: 42
buffer_size: 10000
batch_size: 32
learning_rate: 0.0001

num_episodes: 500
update: 100
target_update: 10

max_history_len: 50

gamma: 0.95
epsilon: 0.03
len_category: 7
len_sub_category: 29
len_industry: 37
dim: 10