seed: 42
buffer_size: 1000
batch_size: 32
learning_rate: 0.0001

num_episodes: 2
# num_iterations:
update_frequency: 50
target_update: 10

worker_num: 1807

max_history_len: 30

gamma: 0.95
epsilon: 0.01
len_category: 7
len_sub_category: 29
len_industry: 37
dim: 30